### ISSUE TITLE
Missing syntax of for loop 

### ISSUE THREAD

**Issue by huyccg** [t-rexdex/A-Place-to-Upload-Colab-.iypnb#1]
@t-rexdex see if you can find the error here
https://github.com/t-rexdex/A-Place-to-Upload-Colab-.iypnb/blob/af8a5079ffd5b49327534a27d87ae04b4e57b1af/main.py#L10

**Comment by t-rexdex** [comment]
Issue has been fixed on line 10 of main.py. Added ':' to the end of line 10 and this change was done through the update branch.
